### ISSUE TITLE
Table Formatting

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/hmpu-workflow#1]
Feature request: Realign group, class, habitat descriptor table rows to resemble the following format: 
[landuse_table_format_example.xlsx](https://github.com/tbep-tech/landuse/files/4047705/landuse_table_format_example.xlsx) .

The FLUCCSCODES in the habitat descriptor categories of "Algae", "Patchy_Seagrass", "Continuous_Seagrass", "Tidal_Flats", "Estuary" should be removed from all the summary tables, and I think that will make the yearly totals more consistent to the total watershed area. 

Salt_Barren acreages for 1990, 1995, and 1999 = 468, 479, 492 respectively. These were developed separately by ESA.

**Comment by fawda123** [comment]
done 26202062fa45475ff51142d4f4b4e665fe8649b1

I'm still messing with the format of the tables, but I took a stab at it using [reactable](https://glin.github.io/reactable/index.html)

**Comment by esherwoo77** [comment]
@fawda123 The subtidal FLUCCSCODES should be removed from the "Class" and "Group" tables (similar to what you did for the "Descriptor" table. This should bring all the yearly Total acreages rows to be in-line with each other.

**Comment by fawda123** [comment]
@esherwoo77 I think it's right now.  I had to remove oyster bars and hard bottom from the descriptor field.  These were under the subtidal class.  All the watershed totals are close to 1450000 acres/2200 sq miles.  

ab4f8098445d7604f67b38e2ecbdd26460f5f6ed
